- name: Ensure PGP key is installed
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    id: 548C16BF
    state: present

- name: Ensure the New Relic APT-repository is added
  apt_repository:
    repo: 'deb http://apt.newrelic.com/debian/ newrelic non-free'
  notify: Update apt

- name: Install New Relic
  apt: name=newrelic-sysmond state=present
  register: new_relic_install

- name: Copy the configuration file
  template: src=nrsysmond.cfg.j2 dest=/etc/newrelic/nrsysmond.cfg
  when: new_relic_install.changed

- name: Ensure New Relic is running
  service: name=newrelic-sysmond state=started enabled=yes
  when: new_relic_install.changed
