---
- name: Set-up adams, the secondary VM
  hosts: adams
  user: root


  roles:
    - sshkeys
    - role: kerberos_server
      tags:
        - kerberos_server

    - role: postfix
      postfix_mailname: adams.ugent.be
      postfix_hostname: adams.ugent.be
      postfix_alias_maps:
        - "hash:/etc/aliases"
        - "pgsql:/etc/postfix/zauth"
      postfix_destinations:
        - zeus.ugent.be
        - localhost
        - adams.ugent.be
        - king.ugent.be
        - kelder.zeus.ugent.be
      postfix_fallback: #Geen
      tags: postfix

    - role: nginx_base
      tags: nginx

    - role: nginx_vhost
      nginx_vhost_file: 'oauth'
      tags:
        - oauth
        - nginx

  vars_files:
    - vars/authorized_keys.yml
