---
- name: Set-up adams, the secondary VM
  hosts: adams
  user: root

  vars_files:
    - vars/authorized_keys.yml
    - vars/secrets.yml

  roles:
    - role: sshkeys
      tags: sshkeys

    - role: alloy
      tags: alloy

    - role: etc
      tags:
        - etc
        - prometheus
      directory: prometheus

    - role: nginx_base
      tags: nginx

    - role: nginx_vhost
      nginx_vhost_file: 'oauth'
      tags:
        - oauth
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'grafana.zeus.gent'
      tags:
        - grafana
        - monitoring
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'prometheus.zeus.gent'
      tags:
        - prometheus
        - monitoring
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'ci.zeus.gent'
      tags:
        - woodpecker
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'docs.zeus.gent'
      tags:
        - docs
        - nginx

    - role: quadlet_host
      container_name: 'woodpecker'
      tags:
        - quadlet
        - woodpecker

    - role: quadlet_host
      container_name: 'woodpecker-agent'
      tags:
        - quadlet
        - woodpecker

    - role: quadlet_host
      container_name: 'grafana'
      tags:
        - quadlet
        - grafana
        - monitoring

    - role: quadlet_host
      container_name: 'prometheus'
      tags:
        - quadlet
        - prometheus
        - monitoring
