---
- name: Raise dick!
  hosts: dickens
  user: root

  vars_files:
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install utilities
      apt:
        name:
          - ack-grep
          - vim
          - zsh
          - tmux
          - htop
          - tree
          - curl
          - unzip
          - etckeeper
          - git-core
          - nmap
          - sudo

  roles:
    - role: sshkeys
      tags: sshkeys

    - role: fail2ban
      tags: fail2ban

    - role: nginx_vhost
      nginx_vhost_file: 'kelder.zeus.ugent.be'
      tags:
        - nginx

    - role: immobulus
      immobulus_ssh_public_key: 'ssh-rsa AAAAC3NzaC1lZDI1NTE5AAAAIO6ANUO7C2vNc3BTHqu/n8mVredVn8y2hqQp4SIYrifY'
      tags: ['immobulus']
