---
- name: Set-up Herbert, the best VM
  hosts: herbert
  user: root

  vars_files:
    - vars/secrets.yml
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install utilities
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ack-grep
        - vim
        - zsh
        - tmux
        - htop
        - tree
        - curl
        - unrar
        - unzip
        - etckeeper
        - git-core
        - nodejs
        - yarn
        - speedtest-cli
        - nmap
        - sudo

  roles:
    - role: sshkeys
      tags: sshkeys

    - role: fail2ban
      tags: fail2ban

    # Install database server
    # - role: geerlingguy.mysql
    #   tags: db
    

    # Add users
    - role: mysql_configs
      tags: db

    - role: alloy
      tags: alloy

    # gitlab uses symlinks, which CIFS does not support
    # so we just mount it
    - role: cifs_share
      share:
        name: battlebots-data
        dest: /mnt/battlebots
        username: "{{ gitlab.share_username }}"
        password: "{{ gitlab.share_password }}"
        owner: root
        group: root
        dir_mode: '0770'
        file_mode: '0660'
      tags:
        - shares
        - gitlab

    ################
    # pr.zeus.gent #
    ################

    - role: user
      user_name: zeuspr
      user_shell: /bin/sh
      user_directories:
        - directory: 'public'
          group: 'www-data'
      user_authorized_keys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1XoPJu+IeqcjDHmzDCwPbRll50sc89eEM/jxGqf/oRLC3i+Iy5HrnMyC01IvMWkMxKkU6aS3yieh+TQvI3+vb3j3wCgsE7YKwWon8Bzya/IW8xUHFXIKINqf6JOoaDMhSZnamuSzSCLzQrrQW9wF+Hk2dSPLIkHBJoXkoNKyruTEdtaFiows9fzj14K0ONOsEyRqYZtkda29Z8Q2JKbGqNZrJzT8walwJt7Sjphxb3wovhRzF6Y9h4lgRQREAxekTbBwT9+SM+DEKMSMMS8xFeCYRYbdi6GJdpl/A6XVnJ15hdSUvbUZ7cFp0bo2Ji3jdwiojyHkHRJo2tA14HuGN13yc7fvkDAPEWncf155kFlUEzJkcELagSwNKHVDGMQmNsmoje3raWAdFDvcZ2qZ3wId7eKi3Onml9QC4vIUGz8AAUw5Oo1HQDKdc0s6PTHByDWWE7L7lhpjpMS0wcRu+Zpd28D9YAyDxccDxC68jPloYi66Wx7tDpVaGpY5OFqRr49VL800QKvgkJAodDWBqbOtw6MgTAgzfOh88YNPeQwx3AZxDfxuLl6ekb93agNMqd7N1rf7zUIyE89Ddyyjl2/sW8kaktwlFEYGaPH8Emsv4kp1s8xtVgTUinQ2KQDK5TJANqLR3CyWFHabRUt8YGddKZnPSjCY73HsdBTuFIQ=='
      tags:
        - pr
        - user

    - role: nginx_vhost
      nginx_vhost_file: 'pr.zeus.gent'
      tags:
        - nginx
        - pr

    ###########
    # postfix #
    ###########

    - role: postfix
      postfix_mailname: herbert.ugent.be
      postfix_hostname: herbert.ugent.be
      postfix_alias_maps:
        - "hash:/etc/aliases"
      postfix_destinations:
        - localhost
        - herbert.ugent.be
      postfix_fallback: #Geen
      filter_spam: False
      tags: postfix

      #######
      # tab #
      #######

    - role: user
      user_name: tab
      user_directories:
        - directory: 'log'
      tags:
        - tab
        - user

    # TODO automate capistrano deploy
    - role: nginx_vhost
      nginx_vhost_file: 'tab.zeus.gent'
      tags:
        - nginx
        - tab

    #######
    # tap #
    #######

    - role: user
      user_name: tap
      user_directories:
        - directory: 'log'
      tags:
        - tap
        - user

    # TODO automate capistrano deploy
    - role: nginx_vhost
      nginx_vhost_file: 'tap.zeus.gent'
      tags:
        - nginx
        - tap

    ###########
    # blokmap #
    ###########

    - role: user
      user_name: blok
      user_directories:
          - directory: 'log'
          - directory: 'log_blokmap.be'
          - directory: 'public'
      tags:
          - blok
          - user

    # This git clones and updates the version of blokmap on the server
    - role: blok
      tags: blok

    - role: nginx_vhost
      nginx_vhost_file: 'blok.ugent.be'
      tags:
          - nginx
          - blok

    - role: nginx_vhost
      nginx_vhost_file: 'blokmap.be'
      tags:
          - nginx
          - blok

    ##############
    # Mattermost #
    ##############

    - role: user
      user_name: mattermost
      tags:
          - mattermost
          - user

    - role: nginx_vhost
      nginx_vhost_file: 'mattermost.zeus.gent'
      tags:
        - nginx
        - mattermost

    ##############
    # Mattermore #
    ##############
    #
    # = mattermost integrations
    #

    - role: user
      user_name: mattermore
      user_directories:
          - directory: 'log'
          - directory: 'public'
      tags:
          - mattermore
          - user

    - role: nginx_vhost
      nginx_vhost_file: 'mattermore.zeus.gent'
      tags:
        - nginx
        - mattermore

    ###############
    # Endorsement #
    ###############

    - role: user
      user_name: endorsement
      user_directories:
          - directory: 'log'
          - directory: 'public'
      tags:
          - endorsement
          - user

    - role: nginx_vhost
      nginx_vhost_file: 'endorsement.zeus.gent'
      tags:
        - nginx
        - endorsement

    - role: user
      user_name: matterircd
      user_directories:
        - directory: 'log'
        - directory: 'public'
      tags:
        - matterircd
        - user

    - role: nginx_vhost
      nginx_vhost_file: 'irc.zeus.gent'
      tags:
          - nginx
          - matterircd

    #######
    # Cat #
    #######
    #
    # : The bestest
    #

    - role: user
      user_name: cat
      tags:
        - cat
        - user

    # - role: ansible_cat
    #   cat_app_host: "https://cat.zeus.gent"
    #   cat_app_port: 3636
    #   oauth_consumer_key: "{{ cat_oauth_consumer_key }}"
    #   oauth_consumer_secret: "{{ cat_oauth_consumer_secret }}"
    #   mariadb_root_password: "{{ mysql_root_password }}"
    #   cat_db_password: "{{ secret_cat_db_password }}"
    #   cat_db_user: "{{ secret_cat_db_user }}"
    #   tags:
    #       - cat

    - role: nginx_vhost
      nginx_vhost_file: 'cat.zeus.gent'
      tags:
          - nginx
          - cat

    #########
    # Tappb #
    #########

    - role: user
      user_name: tabbp
      user_directories:
        - directory: 'log'
        - directory: 'public'
      tags:
        - tabbp
        - user

    - role: nginx_vhost
      nginx_vhost_file: 'tabbp.zeus.gent'
      tags:
       - nginx
       - tabbp


    ##############
    # Hookermost #
    ##############

    - role: hookermost
      tags: hookermost

    - role: nginx_vhost
      nginx_vhost_file: 'hookermost.zeus.gent'
      tags:
       - nginx
       - hookermost


    ###########
    # Strobot #
    ###########

    - role: user
      user_name: strobot
      tags:
        - user
        - strobot

    ##########
    # TORGAX #
    ##########

    - role: user
      user_name: torgax
      user_directories:
          - directory: 'log'
          - directory: 'public'
      tags:
          - torgax
          - user

    - role: nginx_vhost
      nginx_vhost_file: 'torgax.zeus.gent'
      tags:
        - nginx
        - torgax

    - role: nginx_vhost
      nginx_vhost_file: 'passenger_config'
      tags:
        - nginx
        - passenger_logs

    - role: nginx_vhost
      nginx_vhost_file: 'vote.zeus.ugent.be'
      tags:
        - nginx
        - vote

    ############
    # Blokdata #
    ############

    - role: user
      user_name: blokdata
      user_directories:
        - directory: 'log'
        - directory: 'public'
        - directory: 'cache'
      tags:
        - blokdata
        - user

    - role: nginx_vhost
      nginx_vhost_file: 'blokdata.zeus.gent'
      tags:
        - blokdata
        - nginx

    - role: nginx_base
      tags:
        - nginx_base

    ########
    # Kers #
    ########

    - role: nginx_vhost
      nginx_vhost_file: 'kers.zeus.gent'
      tags:
        - nginx
        - kers

    #########
    # moana #
    #########

    - role: nginx_vhost
      nginx_vhost_file: 'moana.zeus.gent'
      tags:
        - nginx
        - moana

    ##############
    # Drive wiki #
    ##############

    - role: user
      user_name: drive
      user_directories:
          - directory: 'log'
          - directory: 'public'
      tags:
          - drive
          - user

    - role: nginx_vhost
      nginx_vhost_file: 'drive.zeus.gent'
      tags:
        - drive
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'redirects.conf'
      tags:
       - nginx
       - redirects

    - role: nginx_vhost
      nginx_vhost_file: 'multiplayer-ruffle-demo.zeus.gent'
      tags:
        - nginx
        - multiplayer-ruffle-demo
