---
- name: Set-up the king
  hosts: king
  user: root

  roles:
      - role: sshkeys
      - role: caddy
        tags: caddy
      - role: postfix
        tags: postfix
      
  vars_files:
      - vars/authorized_keys.yml
