---
- name: Set-up the king
  hosts: king
  user: root

  vars_files:
      - vars/authorized_keys.yml
      - vars/secrets.yml

  roles:
    - role: sshkeys
    - role: caddy
      tags: caddy

    - role: postfix
      tags: postfix

    - role: alloy
      tags: alloy

    - role: quadlet_host
      container_name: 'postgresql'
      tags:
        - quadlet
      
    - role: quadlet_host
      container_name: 'rspamd'
      tags:
        - quadlet

    - role: quadlet_host
      container_name: 'unbound'
      tags:
        - quadlet

    - role: quadlet_host
      container_name: 'zauth'
      tags:
        - quadlet

    - role: quadlet_host
      container_name: 'zauth'
      tags:
        - quadlet

    - role: quadlet_host
      container_name: 'postsrsd'
      tags:
        - quadlet

