---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root


  roles:
#    - sshkeys
#    - common
#    - users
#    - mariadb
#    - iptables
#    - nginx_base
#    - php
#    # Email stuff
#    - spamassassin
#    - mail_antivirus
#    - role: postfix
#    - mailman
#    - fail2ban
#    - ntp
#    # Ruby, rails, passenger stuff
#    - zzet.rbenv
#    - bundler # enable this when installing a new rbenv version using zzet.rbenv
#    - common-rails
#    - passenger
#    # User configs and stuff
#    - mysql_configs
   - nginx_sites_king

  vars_files:
    - vars/passwords.yml
    - vars/ruby.yml
    - vars/authorized_keys.yml
