---
- name: Set-up the king
  hosts: king
  user: root

  roles:
      - role: sshkeys
      - role: caddy
        tags: caddy
      
#    - common
#    - nginx_base
#    # Email stuff
#    - spamassassin
#    - mail_antivirus
#    - role: postfix
#    - mailman
#    - fail2ban
#    - ntp
#    # User configs and stuff
#    - mysql_configs

  vars_files:
      - vars/authorized_keys.yml
