---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root


  roles:
     - role: sshkeys
       extra_keys: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1i4fno93sR9g9Vepd5VGCTSjEzqdwM+X1UXPLQipy9 mathieu@ms-laptop'
#    - common
#    - nginx_base
#    # Email stuff
#    - spamassassin
#    - mail_antivirus
#    - role: postfix
#    - mailman
#    - fail2ban
#    - ntp
#    # User configs and stuff
#    - mysql_configs
     - nginx_sites_king

  vars_files:
    - vars/ruby.yml
    - vars/authorized_keys.yml
