---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root


  roles:
   - sshkeys
#    - common
#    - nginx_base
#    # Email stuff
#    - spamassassin
#    - mail_antivirus
#    - role: postfix
#    - mailman
#    - fail2ban
#    - ntp
#    # User configs and stuff
#    - mysql_configs
   - nginx_sites_king

  vars_files:
    - vars/ruby.yml
    - vars/authorized_keys.yml
