---
- name: Configure Pratchett
  hosts: pratchett
  user: root

  vars_files:
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install utilities
      apt:
        name:
          - ack-grep
          - vim
          - zsh
          - tmux
          - htop
          - tree
          - curl
          - unzip
          - etckeeper
          - git-core
          - nmap
          - sudo

  roles:
    - role: sshkeys
      tags: sshkeys

    - role: nginx_base
      tags: nginx_base

    - role: nginx_vhost
      nginx_vhost_file: 'lucht.zeus.ugent.be'
      tags:
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'codimd.zeus.gent'
      tags:
        - nginx
        - codimd

    - role: nginx_vhost
      nginx_vhost_file: 'g2-api.zeus.gent'
      tags:
        - nginx
        - g2

    - role: nginx_vhost
      nginx_vhost_file: 'g2.zeus.gent'
      tags:
        - nginx
        - g2

    - role: nginx_vhost
      nginx_vhost_file: 'verify.pratchett.zeus.gent'
      tags:
        - nginx

    - role: nginx_vhost
      nginx_vhost_file: 'avatar.pratchett.zeus.gent'
      tags:
        - nginx
        - avatar

    - role: nginx_vhost
      nginx_vhost_file: 'tractor.pratchett.zeus.gent'
      tags:
        - nginx
        - tractor

    - role: nginx_vhost
      nginx_vhost_file: 'massacantus'
      tags:
        - nginx
        - massacantus

    - role: nginx_vhost
      nginx_vhost_file: 'factuur.12urenloop.be'
      tags:
        - nginx
        - 12urenloop
        - factuur

    - role: nginx_vhost
      nginx_vhost_file: 'join.12urenloop.be'
      tags:
        - nginx
        - 12urenloop
        - join

    - role: nginx_vhost
      nginx_vhost_file: '12urenloop.be'
      tags:
        - nginx
        - 12urenloop
        - urenloop-site

    - role: nginx_vhost
      nginx_vhost_file: 'msrs.zeus.gent'
      tags:
        - nginx
        - msrs

    - role: nginx_vhost
      nginx_vhost_file: 'wiki.zeus.gent'
      tags:
        - nginx
        - wiki

    - role: nginx_vhost
      nginx_vhost_file: 'hydra-admin.zeus.gent'
      tags:
        - nginx
        - hydra-admin
