---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
    - common
    - users
    - mysql
    - nginx
    - php
    - passenger
    - python
    - postfix
    - nginx_configs
    - new_relic
    - fail2ban
