---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
    - common
    - users
    - mysql
    - nginx
    - php
    - passenger
    - rvm_ruby_rails
    - python
    - nginx_configs
