---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
    - common
    - users
    - logrotate
    - kerberos
    - mysql
    - iptables
    - nginx
    - php
    - python
    # Email stuff
    - spamassassin
    - postfix
    - mailman
    - mediawiki
    - nginx_configs
    - mysql_configs
    - new_relic
    - fail2ban
    - django_configs
    - phpmyadmin
    - crontab
    - ntp
    # Ruby, rails, passenger stuff
    - { role: rvm, tags: ruby, sudo: True }
    - passenger
    - imagemagick
  vars_files:
    - vars/passwords.yml
