---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
#    - common
#    - franklinkim.sudo
#    - users
#    - logrotate
#    - kerberos
#    - mysql
#    - iptables
#    - nginx
#    - php
#    - python
#    # Email stuff
#    - spamassassin
#    - postfix
#    - mailman
#    - new_relic
#    - fail2ban
#    - phpmyadmin
#    - crontab
#    - ntp
#    # Ruby, rails, passenger stuff
#    - { role: zzet.rbenv, rbenv.ruby-version: 2.2.0 }
#    - passenger
#    - imagemagick  # Dependency for Rails
#    # User configs and stuff
#    - mysql_configs
#    - nginx_configs
#    - django_configs
#    - user_configs
#    - dokuwiki
  vars_files:
    - vars/passwords.yml
