---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
    - common
    - users
    - mysql
    - nginx
    - php
    - passenger
    - python
    - postfix
    - mailman
    - nginx_configs
    - new_relic
    - fail2ban

  vars_prompt:
    - name: "mailman_password"
      prompt: "Enter mailman admin password"
      private: yes
