---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
    - common
    - users
    - logrotate
    - ruby
    - mysql
    - iptables
    - nginx
    - ruby
    - php
    - passenger
    - python
    - postfix
    - mailman
    - mediawiki
    - nginx_configs
    - new_relic
    - fail2ban
    - django

  vars_prompt:
    - name: "mailman_password"
      prompt: "Enter mailman admin password"
      private: yes

    - name: "mysql_root_password"
      prompt: "Enter the MySQL root password"
      private: yes

    - name: "mediawiki_password"
      prompt: "Enter mediawiki password"
      private: yes
