---
- name: Tolkien, our container park
  hosts: tolkien
  user: root

  vars_files:
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apk:
        update_cache: yes
      tags: update

    - name: Install utilities
      apk:
        name: "{{ item }}"
        state: latest
      with_items:
        - grep
        - vim
        - tmux
        - htop
        - tree
        - curl
        - unzip
        - git
        - speedtest-cli
        - nmap
        - sudo
        - ca-certificates
        - curl
        - gnupg
      tags: utilities

  roles:
    - role: sshkeys
      tags: sshkeys
