---
- name: Install iptables and arno-iptables
  apt: name={{ item }} state=present
  with_items:
    - iptables
    - arno-iptables-firewall
  notify:
    - Restart arno-iptables

- name: Copy config files
  copy: src={{ item }} dest=/etc/arno-iptables-firewall/{{ item }}
  with_items:
    - blocked_hosts
  notify:
    - Restart arno-iptables

- name: Copy conf.d
  copy: src=conf.d/ dest=/etc/arno-iptables-firewall/conf.d/
  notify:
    - Restart arno-iptables
