---
 - name: Check if already installed
   stat: path=/srv/dokuwiki
   register: st

 - name: Download latest stable dokuwiki tarball
   get_url: url=http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz dest=/var/tmp/dokuwiki-stable.tgz
   when: not st.stat.exists

 - name: Unpack tarball
   command: tar -xvf dokuwiki-stable.tgz chdir=/var/tmp
   when: not st.stat.exists

 - name: Prepare target directory
   command: mkdir /srv/dokuwiki
   when: not st.stat.exists

 - name: Move dokuwiki
   shell: mv /var/tmp/dokuwiki*/* /srv/dokuwiki/
   when: not st.stat.exists

 - name: Fix permissions
   shell: chown -R zeusweb:www-data /srv/dokuwiki/{conf,data,lib/{plugins,tpl}}
   notify: restart nginx
   when: not st.stat.exists
