---
- name: Update apt
  apt: update_cache=yes

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{phpma_password}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_root_password}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{phpma_password}}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: Install phpMyAdmin
  apt: name=phpmyadmin state=present

- name: Assure the nginx folder is present
  file: path=/usr/share/nginx/html/  state=directory

- name: Add link so nginx knows what to serve but change the name to avoid bruteforce bot attacks
  file: src=/usr/share/phpmyadmin dest=/usr/share/nginx/html/phpadmin state=link

- name: Toggle mcrypt
  shell: php5enmod mcrypt

- name: Restart the PHP processor
  service: name=php5-fpm state=restarted enabled=yes
