---
# This playbook contains common plays that will be run on all nodes.

- name: Install cmake
  apt: pkg={{ item }} state=present update_cache=yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: package
  with_items:
   - cmake
   - cmake-curses-gui
