---
- name: Enable passenger_root, ruby and mediawiki
  copy: src={{ item}} dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - mediawiki.conf
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy ssl certificate stuff
  copy: src=ssl/ dest=/etc/nginx/ssl/
  notify:
    - Restart nginx

- name: Copy website configs
  copy: src=sites-enabled/ dest=/etc/nginx/sites-enabled/
  notify:
    - Restart FastCGI
    - Restart nginx
