---
- name: Copy ssl certificate stuff
  copy: src=ssl/ dest=/etc/nginx/ssl/
  notify:
    - Restart nginx

- name: Copy socket configs
  copy: src=pools/ dest=/etc/php5/fpm/pool.d/
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy website configs
  copy: src=sites-enabled/ dest=/etc/nginx/sites-available/
  notify:
    - Restart nginx

- name: Copy conf.d configs
  copy: src=conf.d/ dest=/etc/nginx/conf.d/
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy FastCGI configs (1)
  copy: src=fastcgi_params dest=/etc/nginx/fastcgi_params
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy FastCGI configs (2)
  copy: src=fcgiwrap.conf dest=/etc/nginx/fcgiwrap.conf
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Link the configs
  shell: ln -sfn /etc/nginx/sites-available/*conf /etc/nginx/sites-enabled/
  notify:
    - Restart FastCGI
    - Restart nginx
