---
- name: Add users
  user: name={{ item.name }}
        shell=/bin/bash
        password="{{ item.crypted_password|default(omit) }}"
        groups={{ item.groups|default(omit) }}
  with_items: users

- name: Add email forward file (for sendmail)
  copy: content={{ item.email }}
        dest=/home/{{ item.name }}/.forward
        owner={{ item.name }}
        group={{ item.name }}
  with_items: users

- name: Add default folders in home dirs
  file: path=/home/{{ item[0].name }}/{{ item[1] }}
        owner={{ item[0].name }}
        group={{ item[0].name }}
        state=directory
  with_nested:
    - users
    - ['log', 'public']
