---
- name: Update apt
  apt: update_cache=yes

- name: Install packages that don't need configuration
  apt: name={{ item }} state=latest
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev
    - libxml2-dev
    - libxslt-dev
    - mongodb
    - zlib1g-dev

- name: Install wkhtmltopdf (+ dependencies) for Saruman
  apt: name={{ item }} state=latest
  with_items:
    - xvfb  # Fake X server
    - wkhtmltopdf
