---
- name: Update apt
  apt: update_cache=yes

- name: Install some essential packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - zsh
    - htop
    - curl
    - unrar
    - unzip
    - etckeeper
    - python-pip
    - git-core

- name: Install ack
  apt: name=ack-grep state=present
  register: ack_installed

- name: Rename ack-grep to ack
  command: dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
  when: ack_installed.changed
