---
- name: Update apt
  apt: update_cache=yes

- name: Install some essential packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - zsh
    - htop
    - curl
    - etckeeper
    - python-pip
