---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-mysql
    - php5-cli
    - php5-curl
  notify:
    - Restart php5-fpm

# Do this to avoid APT overriding your configurations
- name: Remove default files
  file: path=/etc/nginx/sites-enabled/default state=absent

# Creates /var/run/php5-fpm on boot
- name: Copy custom systemd service file
  copy: src=lib/systemd/system/php5-fpm.service dest=/lib/systemd/system/php5-fpm.service
  notify:
    - Restart php5-fpm

# This will set up FastCGI with PHP
- name: Copy the custom configuration
  copy: src=etc/nginx/sites-available/my-default dest=/etc/nginx/sites-available/my-default
  notify:
    - Restart php5-fpm
    - Restart nginx

- name: Link default file
  file: src=/etc/nginx/sites-available/my-default dest=/etc/nginx/sites-enabled/default state=link

- name: Create php5-fpm configuration file
  copy: src=etc/php5/fpm/pool.d/www.conf dest=/etc/php5/fpm/pool.d/www.conf
  notify:
    - Restart php5-fpm
    - Restart nginx
