---
- name: Install virtualenv for Django users
  shell: su {{ item.name }} -c "virtualenv /home/{{ item.name }}/.venv"
  args:
    creates: /home/{{ item.name }}/.venv
  with_items: users
  when: item.django is defined

- name: Ensure virtualenv activation is part of bashrc
  lineinfile:
    dest=/home/{{ item.name }}/.bashrc
    line='source ~/.venv/bin/activate'
    state=present
  with_items: users
  when: item.django is defined
