---
- name: Install some default folder for Capistrano
  file:
    path: /home/{{ item.name }}/production/shared/config/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: users
  when: item.rails is defined

- stat: path=/home/{{ item.name }}/production/shared/config/database.yml
  register: database_exists
  with_items: users

- name: Install shared database.yml for Capistrano
  template: src=database.yml.j2 dest=/home/{{ item.item.name }}/production/shared/config/database.yml
            owner={{ item.item.name }} group={{ item.item.name }} mode=644
  when: item.item.rails is defined and not item.stat.exists
  with_items: database_exists.results

- stat: path=/home/{{ item.name }}/production/shared/config/secrets.yml
  register: secrets_exists
  with_items: users

- name: Install shared secrets.yml for Capistrano
  template: src=secrets.yml.j2 dest=/home/{{ item.item.name }}/production/shared/config/secrets.yml
            owner={{ item.item.name }} group={{ item.item.name }} mode=644
  when: item.item.rails is defined and not item.stat.exists
  with_items: secrets_exists.results
