---
- name: Install some default folder for Capistrano
  file:
    path: /home/{{ item.name }}/production/shared/config/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: users
  when: item.rails is defined

- name: Install shared files for Capistrano
  template: force=no src={{ item[1] }}.j2 dest=/home/{{ item[0].name }}/production/shared/config/{{ item[1] }}
            owner={{ item[0].name }} group={{ item[0].name }} mode=644
  when: item[0].rails is defined
  with_nested:
    -  users
    - ['database.yml', 'secrets.yml']
