---
- name: Install some default folder for Capistrano
  file:
    path: /home/{{ item.name }}/production/shared/config/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: users
  when: item.rails is defined

- name: Install shared database.yml for Capistrano
  template: force=no src=database.yml.j2 dest=/home/{{ item.name }}/production/shared/config/database.yml
            owner={{ item.name }} group={{ item.name }} mode=644
  when: item.rails is defined
  with_items: users

- name: Install shared secrets.yml for Capistrano
  template: force=no src=secrets.yml.j2 dest=/home/{{ item.name }}/production/shared/config/secrets.yml
            owner={{ item.name }} group={{ item.name }} mode=644
  when: item.rails is defined
  with_items: users
