---
- name: Install mediawiki
  apt: name=mediawiki state=present
  register: mediawiki_install

- name: Ensure MySQL is running
  service: name=mysql state=started enabled=yes
  when: mediawiki_install.changed

- name: Create the mediawiki database
  mysql_db: login_user=root login_password='{{ mysql_root_password }}' name=mediawiki state=present
  when: mediawiki_install.changed

- name: Add the mediawiki MySQL user
  mysql_user: login_user=root login_password='{{ mysql_root_password }}' name=wikiuser password={{ mediawiki_password }} priv="mediawiki.*:index,create,select,insert,update,delete,alter,lock tables" state=present
  when: mediawiki_install.changed

- name: Run the install script
  shell: php /var/lib/mediawiki/maintenance/install.php "Zeus Wiki" "wikiuser"
  when: mediawiki_install.changed

- name: Override LocalSettings.php with our own settings
  copy: src=LocalSettings.php dest=/usr/share/mediawiki/
  when: mediawiki_install.changed

- name: Fill in the MySQL password
  shell: sed -i 's,password = ,&"{{ mediawiki_password  }}",' /usr/share/mediawiki/LocalSettings.php
  when: mediawiki_install.changed

- name: Add LdapAuthentication
  copy: src=ldapauth/ dest=/usr/share/mediawiki-extensions/
  when: mediawiki_install.changed

- name: Add links
  file: src=/usr/share/mediawiki-extensions/{{ item }} dest=/etc/mediawiki-extensions/extensions-available/{{ item }} state=link
  when: mediawiki_install.changed
  with_items:
    - LdapAuthentication.php
    - LdapAutoAuthentication.php

- name: Enable extensions
  file: src=/etc/mediawiki-extensions/extensions-available/{{ item }}  dest=/etc/mediawiki-extensions/extensions-enabled/{{ item }} state=link
  when: mediawiki_install.changed
  with_items:
    - Cite.php
    - Footnote.php
    - LdapAuthentication.php
    - LdapAutoAuthentication.php
    - NewestPages.php
    - NewUserNotif.php
    - RSSReader.php
